### ISSUE TITLE
paste plugin: Do not send a leading newline when there is only one line to paste

### ISSUE THREAD

**Issue by rumpelsepp** [boothj5/profanity-plugins#5]
See subject, I think it describes everything. :)

**Comment by ikr** [comment]
Same for `syscmd.py`,

```
/system exec ...
/system send ...
```
both send a leading new-line before the script output

**Comment by boothj5** [comment]
The paste plugin no longer sends a leading newline for single line text.  The newline can also be disabled for multi line text using `/paste newline off`

Created a separate issue for `syscmd.py`.
